schema-version: v2
kind: plugin
metadata:
  name: java-spring-security-oauth2-plugin
  display-name: java-spring-security-oauth2-resourceserver-plugin
  description: Plugin to enable and configure Spring Security OAuth2 Resource Server in Java Spring Boot applications
  version: 0.0.1
  picture: plugin.png
spec:
  type: app
  compatibility:
    - maven
    - application.yaml
    - java
    - spring
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes-0.0.1.md
  requirements: docs/requirements.md
  single-use: False
  repository: git@github.com:rafaelpontezup/coffee-studio.git
  technologies: # Ref: https://docs.stackspot.com/create-use/create-content/yaml-files/plugin-yaml/#technologies-1
    - Api
  stk-projects-only: false
  
  computed-inputs:
    project_base_package: "{{global_cs_project_base_package}}"
    project_base_package_dir: "{{global_cs_project_base_package_dir}}"
    src_test_application_test_java_classpath_dir: "src/test/java/{{global_cs_application_test_java_classpath_dir}}"

  hooks:
    ##
    # Edit application.yaml
    ##
    - type: edit
      path: src/main/resources/application.yaml
      trigger: after-render    
      changes:
        - search:
            string: "spring:"
            insert-after:
              snippet: snippets/snippet-application.yaml
            when:
              not-exists: "resourceserver:"
    ##
    # Edit pom.xml
    ##
    - type: edit
      path: pom.xml
      trigger: after-render    
      changes:
        - search:
            string: "</dependencies>"
            insert-before:
              snippet: snippets/snippet-pom.xml
            when:
              not-exists-snippet: snippets/snippet-pom.xml
    ##
    # Create or edit docker-compose.yaml
    ##
    - type: render-templates
      trigger: after-render
      path: snippets/docker-keycloak
    ##
    # Edit {AppName}ApplicationTests.java
    ##
    - type: edit
      path: "{{src_test_application_test_java_classpath_dir}}"
      trigger: after-render
      changes:
        - search:
            string: "private void _assertPropertyEquals("
            insert-before:
              snippet: snippets/snippet-application-test-class.java.jinja
              when:
                not-exists: "void validateSpringSecurityOAuth2ResourceServerPluginConfig()"