schema-version: v2
kind: plugin
metadata:
  name: java-springboot-restapi-base-plugin
  display-name: Java and Spring Boot REST API Base plugin
  description: Base plugin for bulding REST API applications with Java and Spring Boot
  version: 1.0.0
  picture: plugin-base.png
spec:
  type: app
  compatibility:
    - java
    - spring
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes-0.0.1.md
  requirements: docs/requirements.md
  repository: https://github.com/rafaelpontezup/java-springboot-restapi-base-plugin
  technologies: # Ref: https://docs.stackspot.com/content-creator/studio/yaml-files/plugin-yaml/#technologies
    - api
    - docker
    - rest
    - spring boot
  inputs:
    - label: Project name
      type: text
      name: project_name
      required: true
      default: springboot-restapi-app
      help: The project name. For example, "my-project" or "super-app".
    - label: Project description
      type: text
      name: project_description
      default: Simple REST API application with Java and Spring Boot
    - label: Spring Boot version
      type: text
      name: project_springboot_version
      default: 2.7.2
      required: true
      help: The Spring Boot version. There's no guarantee it works with other newer versions, such as v3.x.
    - label: Project groupId
      type: text
      name: project_group_id
      required: true
      default: br.com.zup.edu
      help: The Maven groupId property. It is your project's base package. For example, "br.com.zup.edu".
    - label: Project artifactId
      type: text
      name: project_artifact_id
      default: springboot-restapi-app
      required: true
      help: The Maven artifactId property. It is the name of the jar without version, and it will also be concatenated with the project group_id.
    - label: Project version
      type: text
      name: project_version
      default: 0.0.1-SNAPSHOT
      required: true
      help: The Maven version property.
  computed-inputs:
    project_artifact_id_formatted: "{{project_artifact_id | lower | to_kebab}}"
    project_artifact_id_sanitized: "{{project_artifact_id_formatted | regex_replace('[^0-9a-zA-Z_]', '')}}"
    project_base_package: "{{project_group_id}}.{{project_artifact_id_sanitized}}"
    project_base_package_dir: "{{project_base_package | group_id_folder}}"
    project_name_capitalized: "{{project_name | to_camel}}"
  global-computed-inputs:
    global_cs_project_name: "{{project_name}}"
    global_cs_project_artifact_id: "{{project_artifact_id_formatted}}"
    global_cs_project_artifact_id_sanitized: "{{project_artifact_id_sanitized}}"
    global_cs_project_java_version: "17"
    global_cs_project_springboot_version: "{{project_springboot_version}}"
    global_cs_project_base_package: "{{project_base_package}}"
    global_cs_project_base_package_dir: "{{project_base_package_dir}}"
    global_cs_application_java_classname: "{{project_name_capitalized}}Application.java"
    global_cs_application_java_classpath: "{{global_cs_project_base_package}}.{{global_cs_application_java_classname}}"
    global_cs_application_java_classpath_dir: "{{global_cs_project_base_package_dir}}/{{global_cs_application_java_classname}}"
  hooks:
    - type: run
      trigger: after-render
      commands:
        - chmod +x mvnw mvnw.cmd